name: Node_CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      NODE_ENV: ci
      PORT: 3000
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with
          node-version: 8
      - run: npm ci
      - run: npm run build
      - run: npm run test