name: Node_CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node_CI
    env: 
      NODE_ENV=ci
      PORT=3000
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'
        run: npm install
        run: npm run build
        run: nohup npm test &
        run: sleep 3
        run: npm run test

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
