name: Node_CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node_CI
    env: 
      NODE_ENV: ci
      PORT: 3000
    steps:
      - uses: actions/checkout@v2
      - run: |
        npm install
        npm run build
        nohup npm test &
        sleep 3
        npm run test