name: Node_CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      NODE_ENV: ci
      PORT: 3000
    steps:
      - uses: actions/checkout@v2
      - name: Node in GitHub Actions
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.3.0
      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.1.0
      - name: Install npm dependencies
        run: npm ci
      - name: Install and Build
        run: npm run build
      - name: Running Tests
        run: npm run test